version: '3.8'


services:
  #PostgresSQL
  postgres:
    container_name: postgres_container
    image:  postgres:14.1-alpine
    restart: unless-stopped
    env_file:
      - './database.env'
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - db-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.18
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - './pgadmin.env'
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db-network
networks:
  db-network:
    driver: bridge
volumes:
  db-data:
  pgadmin-data: